config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tweets#index'
  #root 'conversations#index'
  #get '/tweets', to: 'tweets#index'
  resources :tweets
  resources :relationships, only: [:create, :destroy]
  get 'followers', to: 'relationships#followers'
  get 'following', to: 'relationships#show'

  resources :conversations do
    resources :messages
  end


  namespace :api do
    namespace :v1 do
      resources :tweets, only: [:index, :show, :create, :destroy]
      #resources :relationships, only: [:destroy]
      #post 'relation',to: 'relationships#destroy'
      post 'sign_up', to: 'users#create'
      post 'sign_in', to: 'users#login'
      post 'relationship', to: 'relationships#create'
      get 'follower', to: 'relationships#follower'
      get 'following', to: 'relationships#following'
      get 'tweets_list', to: 'relationships#tweets_list'
      post 'like', to: 'likes#create'
      get 'hashtag', to: 'tweets#src_hashtag'

      resources :conversations,  only: [:index, :create]
      #resources :messages,  only: [:index, :show, :create]
      

      get 'conversations/messages', to: 'messages#index'
      get 'conversations/message', to: 'messages#show'
      post 'conversations/newmsg', to: 'messages#create'
      # get 'conversations', to: 'conversations#index'
      # post 'conversation', to: 'conversations#create'
    end
  end




end

app/models/tweet.rb
class Tweet < ApplicationRecord
    #Validations
    validates :text, presence: true
    validates :username, presence: true
    validates :user_id, presence: true
    validates :text, length: { maximum: 280 }


    #Associations
    #User:Tweet
    belongs_to :user


    #Restrictions

    #before_actions
    
    #before_update

end

app/controllers/api/v1/tweets_controller.rb
module Api
    module V1
        class TweetsController < ApiController
            before_action :get_tweet, only: [:show, :destroy]

            #GET api/v1/tweets
            def index
                #@tweets = Tweet.where(user_id: current_user.id)
                @tweets = current_user.tweets
                render json: @tweets

                #@tweets = current_user.tweets
            end
        
            #GET api/v1/tweets/:id
            def show
                render json: @tweet
                # if tweet
                #     render json: @tweet
                # else
                #     render json: {error: 'Tweet not found', status: 404}
                # end
            end
        
            def src_hashtag
                @hashtag = []
                @texto = []
                @tweet = Tweet.all
                @tweet.each do |tweet|
                    @hashtag = tweet.text.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}  
                    @hashtag.each do |hashtag|
                        if hashtag == params[:text]
                            @texto << tweet
                        end
                    end  
                end
                render json: @texto
            end

            #POST /api/v1/tweets
            #params(text: "", username: "", user_id: "")
            def create
                @tweet = Tweet.new(tweet_params)
                @tweet.user_id = current_user.id
                @tweet.username = current_user.username
                
                if @tweet.save
                    render json: @tweet, status: :ok
                #     redirect_to tweets_path, notice: "¡Tweet posted!:D"
                else
                    message_error = " "
                    @tweet.errors.full_messages.each do |error|
                        message_error = message_error + " " + error
                    end
                    render error: {error: "message_error", status: 400}
                end
            end


            #DELETE /api/v1/tweets/:id
            def destroy
                @tweet.destroy
                #Destruir el tweet y no hacer nada: 
                #head :no_content
                render json: {response: "Tweet deleted"}, status: 200
            end
        
            private
        
            def tweet_params
                params.require(:tweet).permit(:text)
            end

            def get_tweet
                @tweet = Tweet.find(params[:id])
            end

        end
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!
    before_action :get_tweet, only: [:show, :destroy]

    def index
        #@tweets = Tweet.where(user_id: current_user.id)
        @tweets = Tweet.all
        #@tweets = current_user.tweets
    end

    def show
    end

    def new
        @tweet = Tweet.new
    end


    # t.text "text"
    # t.string "username"
    # t.integer "user_id"
    def create
        @tweet = Tweet.new(tweet_params)
        @tweet.user_id = current_user.id
        @tweet.username = current_user.username
        if @tweet.save
            redirect_to tweets_path, notice: "¡Tweet posted!:D"
        else
            message_error = " "
            @tweet.errors.full_messages.each do |error|
                message_error = message_error + " " + error
            end

            #flash.alert = "Can't tweet an empty tweet"
            flash.alert = message_error
            render :new
            
        end

      


    end

    def destroy
        @tweet.destroy
        redirect_to tweets_path, notice: "¡Tweet deleted!:D"
    end

    private

    def tweet_params
        params.require(:tweet).permit(:text)
    end

    def get_tweet
        @tweet = Tweet.find(params[:id])
    end

end

app/views/tweets/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
.button {
  border: none;
  color: white;
  padding: 8px 14px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  margin: 4px 2px;
  cursor: pointer;
  background-color: #008CBA;
}

</style>
</head>
<body>



<h1> Tweet Index  </h1>
<%= link_to('MailBox', conversations_path())%>

<div>
    <% if user_signed_in? %>
        <%= link_to('Followers', followers_path(id: current_user.id))%>&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp 
        <%= link_to('Following', following_path(id: current_user.id))%>
    <% end %>
</div>


<% @tweets.each do |tweet| %>
    <br/>
    <b>  ------------------------- </b>
    <p><%= tweet.text %> <%= link_to('View Tweet', tweet_path(tweet.id))%>&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp 
    <%= link_to('Delete', tweet_path(tweet.id), method: :delete, data: {confirm: "Are you SURE?"}) unless user_signed_in? && current_user.id != tweet.user.id%>
    <br/> <%= ("@" + tweet.username) if tweet.username != nil %> 
    <% if user_signed_in? && current_user.id != tweet.user.id %>
        <% if !current_user.following?(tweet.user) %>
            <%= button_to "Follow", relationships_path(id: tweet.user.id), {:class => "button" }%>
        <%else%>
            <%= button_to "Unfollow", relationship_path(id: tweet.user.id), method: :delete, :class => "button" %>
        <%end%>
    <%end%>
    </p>
    
<% end %>
<div>
 
</div>

<h2></h2>
<b>  ------------------------- </b>
<br/>
<div>
    <%= link_to('new Tweet', new_tweet_path)%>
</div>